### PR TITLE
Fixed model creation for Django1.8 ContentType change

### PR DESCRIPTION
**Pull request by jonzlin95**
Added in a hook to check for Django version on model creation. Not sure if this is the best way to get V1.8 compatibility, but it works for all my purposes.

Cheers,
Jonathan

### CODE REVIEW

**Comment by spapas** [comment]
@jezdez could you please merge this PR in order to resolve the mention issue ? 

The failed tests doesn't seem to be related to the changes in the PR.

**Comment by aldarund** [comment]
+1

**Comment by michaelkuty** [comment]
+1

**Comment by tomchristie** [comment]
Hi @michaelkuty. I've now blocked you from participating in any of my projects, and I hope @jezdez will do the same for his. Please don't be such an arse in the future.

**Comment by Anton-Shutik** [comment]
@jezdez can you plz merge this PR ?

**Comment by michaelkuty** [comment]
@tomchristie i send email with my apologize, i'm was angry to @jezdez  because https://github.com/django-leonardo/django-leonardo must have two dependencies to git which makes slower installation in the cloud with auto scaling and these two dependencies is under @jezdez  maintenance, as i said @jezdez , if you haven't time to maintain your projects you can may looking for some mainter i see many contributors which yells for new version !
again @tomchristie sorry about my hate

**Comment by tomchristie** [comment]
> i send email with my apologize

@michaelkuty Noted.

> i see many contributors which yells for new version 

If they did, then they'd be adopting the wrong attitude. Users of open source software don't have a right to the maintainer's time. If a change you'd like to see isn't incoming there are productive alternatives. I'd suggest either maintaining a fork, or introducing a hotfix in your codebase that patches the`create_perm` function in the meantime. *Then add a note to the thread about how you've worked around the issue and allow others to do the same if needed.*

You or anyone else could also offer to share maintenance of the project. (Although that still requires effort on the part of the maintainer, and a demonstration of ability, so it's not a cost-free option for the maintainer.)

**Comment by bufke** [comment]
This pull seems to work for me.

For the impatient... https://pypi.python.org/pypi/django-constance-updated

@jezdez I see your name everywhere, thanks for the work you do!

**Comment by tomchristie** [comment]
:+1:

**Comment by enono78** [comment]
+1 thanks

**Comment by michaelkuty** [comment]
@tomchristie still calm ?

**Comment by PetrDlouhy** [comment]
Any update on this?

**Comment by michaelkuty** [comment]
work in progress, i contacted @jezdez about maintenance

**Comment by flxfxp** [comment]
any news on this? I'm getting `django.utils.importlib will be removed in Django 1.9.`

**Comment by camilonova** [comment]
@jezdez thank you so much for your time and work

**Comment by camilonova** [comment]
Any updates?

**Comment by mo-mughrabi** [comment]
+1

**Comment by camilonova** [comment]
@jezdez can I help somehow to make this happen?

**Comment by michaelkuty** [comment]
keep calm @jezdez haven't fifteen minutes on merge

**Comment by tomchristie** [comment]
@michaelkuty - this repeated badgering of yours is really quite obnoxious. There no obligation for anyone else to do some work on your behalf, however trivial you deem it.

There's an alternate pypi package listed this thread, use that if you prefer.

Chill out and stop pestering.

**Comment by jezdez** [comment]
Fixed via other PRs

**Comment by camilonova** [comment]
@jezdez Thank you pal

**Pull request closed without merging**
